-- subquery로 추출 대상 선별, 부모가 rare인 자식 대상 출력
SELECT ii.ITEM_ID, ii.ITEM_NAME, ii.RARITY
FROM ITEM_INFO AS ii JOIN ITEM_TREE AS it ON ii.ITEM_ID = it.ITEM_ID
WHERE it.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY ii.ITEM_ID DESC;