-- 매 row에 대해 전체에서 parent id와 매칭되는 갯수를 반환
SELECT ed.ID, COALESCE(ch.CHILD_COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS ed
LEFT JOIN (SELECT PARENT_ID, COUNT(*) AS CHILD_COUNT FROM ECOLI_DATA GROUP BY PARENT_ID) AS ch ON ed.ID = ch.PARENT_ID
ORDER BY ed.ID ASC;