-- 코드를 입력하세요
SELECT fh.FLAVOR 
FROM FIRST_HALF AS fh JOIN ICECREAM_INFO AS ii on fh.FLAVOR = ii.FLAVOR 
WHERE ii.INGREDIENT_TYPE = 'fruit_based' and fh.TOTAL_ORDER > 3000
ORDER BY fh.TOTAL_ORDER DESC;