-- 상품 판매수 집계 후 상품 테이블 가격과 곱해서 산출
SELECT prod.PRODUCT_CODE, (off.AMOUNT * prod.PRICE) AS SALES
FROM PRODUCT AS prod
JOIN (SELECT PRODUCT_ID, SUM(SALES_AMOUNT) AS AMOUNT FROM OFFLINE_SALE GROUP BY PRODUCT_ID) AS off 
   ON prod.PRODUCT_ID = off.PRODUCT_ID
ORDER BY SALES DESC, prod.PRODUCT_CODE ASC;
