-- 3월 생일자, 여성, 폰번 NULL 아닐 경우 MEMBER_ID 오름차순
SELECT mf.MEMBER_ID, mf.MEMBER_NAME, mf.GENDER, DATE_FORMAT(mf.DATE_OF_BIRTH, '%Y-%m-%d') as DATE_OF_BIRTH
FROM MEMBER_PROFILE as mf
WHERE EXTRACT(MONTH from mf.DATE_OF_BIRTH) = 3 AND mf.GENDER = 'W' AND mf.TLNO IS NOT NULL
ORDER BY mf.MEMBER_ID ASC;