-- PYTHON, C# 중 1개 이상 SKILL_CODE 가진 DEVELOPER 추출 (캐싱되는 subquery)
SELECT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS AS d
WHERE d.SKILL_CODE & (SELECT s.CODE FROM SKILLCODES AS s WHERE s.NAME = 'C#') > 0
   OR d.SKILL_CODE & (SELECT s.CODE FROM SKILLCODES AS s WHERE s.NAME = 'Python') > 0
ORDER BY d.ID ASC;
